name: cooking_recipes_app
description: App for consulting and sharing recipes.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cooking_recipes_components:
    path: packages/cooking_recipes_components

  cupertino_icons: ^1.0.6
  dio: ^5.3.2
  injectable: ^2.3.0
  get_it: ^7.6.4
  equatable: ^2.0.5
  lottie: ^2.6.0
  flutter_feather_icons: ^2.0.0+1
  mobx: ^2.2.0
  flutter_mobx: ^2.0.6+5
  path_provider: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.3
  build_runner: ^2.4.6
  mocktail: ^1.0.0
  injectable_generator: ^2.4.0
  mobx_codegen: ^2.4.0

flutter:
  uses-material-design: true
