name: cooking_recipes_components
description: The package with components to cooking recipes app.
version: 0.0.1

environment:
  sdk: ">=3.1.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  google_fonts: ^6.0.0
  flutter_feather_icons: ^2.0.0+1
  flutter_toggle_tab: ^1.4.1
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3

flutter:
  uses-material-design: true

  assets:
    - assets/animations/
