name: Flutter CI

on:
  push:
    branches: [main]

  pull_request:
    branches: [main]

jobs:
  flutter_CI:
    name: Flutter build, analize and test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup Flutter SDK
      uses: subosito/flutter-action@v2
      with:
        flutter-version: 3.x 

    - name: Install Dependencies
      run: flutter pub get

    - name: Run Flutter Analyze
      run: flutter analyze

    - name: Run Flutter Tests
      run: flutter test
